version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      build-tools:
        patterns: ['*']
    open-pull-requests-limit: 3
